# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: uni_v3
networks:
- id: 1
  start_block: 22026500
  contracts:
  - name: UniswapV3Factory
    address: 0x1F98431c8aD98523631AE4a59f267346ea31F984
    handler: src/EventHandlers.ts
    events:
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: UniswapV3Pool
    handler: src/EventHandlers.ts
    events:
    - event: Initialize(uint160 sqrtPriceX96, int24 tick)


